[客户端自动化配置]
# 设置鼠标移动速度：0为立即执行
duration = 0.2
# 设置键盘按键间隔时间,每次点击时的间隔时间：0为立即执行
interval = 0.25
# 隐式等待时间
minSearchTime = 5
# 设置图片识别信任度
confidence = 0.97
# 是否灰度匹配
grayscale = True

[WEB自动化配置]
#选择浏览器类型：1.IE 2.Chrome 3.Firefox 4.Chrome_headless 5.Firefox_headless
browser=Chrome

[日志打印配置]
format = %(asctime)s - %(name)s - %(levelname)s - %(message)s
level = INFO
stream_handler_level = DEBUG
file_handler_level = DEBUG

[邮件发送配置]
# 地址 smtp.163.com 或者 smtp.qq.com
host = smtp.qq.com
# 端口 25 或者 465 或者 587 或者 993 或者 995 或者 994
port = 465
# 发送方email
send_email = 1070685200@qq.com
# 接收方email,群发是列表形式["xxx","xxx","xxx",...]
receive_email = ['1347530516@qq.com']
# 授权码
pwd = cfucejuagtwhbedg
# 发送方的名字，一般为测试人员
sender = 测试中心 - 工具人
# 主题 格式字符串
subject = %s测试报告

[数据库配置]
dbtype = mysql
host = 127.0.0.1
port = 3306
user = root
password = Wxh123456
database = test
charset = utf8

[项目运行设置]
# 自动化层测试类型：HTTP，WEB，CLIENT
AUTO_TYPE = HTTP
# 测试报告类型：ALLURE，HTML，XML
REPORT_TYPE = HTML
# 数据驱动类型：YamlDriver，ExcelDriver
DATA_DRIVER_TYPE = YamlDriver
# 项目名称：空为全部项目，TestSuits下的文件名
TEST_PROJECT_NAME = p03_http_gjxt
# 项目测试地址
TEST_URL = https://127.0.0.1
# 是否发送邮件：yes， no
SEND_EMAIL = yes

